FROM golang:latest 

WORKDIR /usr/src/app

COPY . . 

ENV GOBIN=/usr/local/bin/ 

RUN ["go", "get", "github.com/githubnemo/CompileDaemon"]
RUN go get -d -v ./...
RUN go install -v ./...

# CMD ["make", "run"]
ENTRYPOINT CompileDaemon -log-prefix=false -build="go build -o bin/exec cmd/main.go" -command="./bin/exec"