FROM python:3

# install dependencies
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# copy src files
COPY . .

# make shell script executable
RUN chmod +x ./run-prod.sh

CMD ./run-prod.sh
