// Code generated by protoc-gen-go. DO NOT EDIT.
// source: imdb.proto

package imdb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenericShowRequest struct {
	ItemId               string   `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericShowRequest) Reset()         { *m = GenericShowRequest{} }
func (m *GenericShowRequest) String() string { return proto.CompactTextString(m) }
func (*GenericShowRequest) ProtoMessage()    {}
func (*GenericShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60183f17d85d4744, []int{0}
}

func (m *GenericShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericShowRequest.Unmarshal(m, b)
}
func (m *GenericShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericShowRequest.Marshal(b, m, deterministic)
}
func (m *GenericShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericShowRequest.Merge(m, src)
}
func (m *GenericShowRequest) XXX_Size() int {
	return xxx_messageInfo_GenericShowRequest.Size(m)
}
func (m *GenericShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenericShowRequest proto.InternalMessageInfo

func (m *GenericShowRequest) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

type CreateShowRequest struct {
	ItemName             string   `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShowRequest) Reset()         { *m = CreateShowRequest{} }
func (m *CreateShowRequest) String() string { return proto.CompactTextString(m) }
func (*CreateShowRequest) ProtoMessage()    {}
func (*CreateShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60183f17d85d4744, []int{1}
}

func (m *CreateShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShowRequest.Unmarshal(m, b)
}
func (m *CreateShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShowRequest.Marshal(b, m, deterministic)
}
func (m *CreateShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShowRequest.Merge(m, src)
}
func (m *CreateShowRequest) XXX_Size() int {
	return xxx_messageInfo_CreateShowRequest.Size(m)
}
func (m *CreateShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShowRequest proto.InternalMessageInfo

func (m *CreateShowRequest) GetItemName() string {
	if m != nil {
		return m.ItemName
	}
	return ""
}

// CreateShowResponse returns necessary information for the client to access
// the resource later.
type CreateShowResponse struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	ItemId               string   `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	TimeCreated          string   `protobuf:"bytes,3,opt,name=time_created,json=timeCreated,proto3" json:"time_created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShowResponse) Reset()         { *m = CreateShowResponse{} }
func (m *CreateShowResponse) String() string { return proto.CompactTextString(m) }
func (*CreateShowResponse) ProtoMessage()    {}
func (*CreateShowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60183f17d85d4744, []int{2}
}

func (m *CreateShowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShowResponse.Unmarshal(m, b)
}
func (m *CreateShowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShowResponse.Marshal(b, m, deterministic)
}
func (m *CreateShowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShowResponse.Merge(m, src)
}
func (m *CreateShowResponse) XXX_Size() int {
	return xxx_messageInfo_CreateShowResponse.Size(m)
}
func (m *CreateShowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShowResponse proto.InternalMessageInfo

func (m *CreateShowResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *CreateShowResponse) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *CreateShowResponse) GetTimeCreated() string {
	if m != nil {
		return m.TimeCreated
	}
	return ""
}

// TVShow schema
type Show struct {
	ItemId               string   `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Show) Reset()         { *m = Show{} }
func (m *Show) String() string { return proto.CompactTextString(m) }
func (*Show) ProtoMessage()    {}
func (*Show) Descriptor() ([]byte, []int) {
	return fileDescriptor_60183f17d85d4744, []int{3}
}

func (m *Show) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Show.Unmarshal(m, b)
}
func (m *Show) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Show.Marshal(b, m, deterministic)
}
func (m *Show) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Show.Merge(m, src)
}
func (m *Show) XXX_Size() int {
	return xxx_messageInfo_Show.Size(m)
}
func (m *Show) XXX_DiscardUnknown() {
	xxx_messageInfo_Show.DiscardUnknown(m)
}

var xxx_messageInfo_Show proto.InternalMessageInfo

func (m *Show) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_60183f17d85d4744, []int{4}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ExtractionRequest struct {
	ItemName             string   `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtractionRequest) Reset()         { *m = ExtractionRequest{} }
func (m *ExtractionRequest) String() string { return proto.CompactTextString(m) }
func (*ExtractionRequest) ProtoMessage()    {}
func (*ExtractionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60183f17d85d4744, []int{5}
}

func (m *ExtractionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtractionRequest.Unmarshal(m, b)
}
func (m *ExtractionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtractionRequest.Marshal(b, m, deterministic)
}
func (m *ExtractionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtractionRequest.Merge(m, src)
}
func (m *ExtractionRequest) XXX_Size() int {
	return xxx_messageInfo_ExtractionRequest.Size(m)
}
func (m *ExtractionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtractionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExtractionRequest proto.InternalMessageInfo

func (m *ExtractionRequest) GetItemName() string {
	if m != nil {
		return m.ItemName
	}
	return ""
}

type ExtractionResponse struct {
	IsItemNameValid      bool     `protobuf:"varint,1,opt,name=is_item_name_valid,json=isItemNameValid,proto3" json:"is_item_name_valid,omitempty"`
	Successful           bool     `protobuf:"varint,2,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtractionResponse) Reset()         { *m = ExtractionResponse{} }
func (m *ExtractionResponse) String() string { return proto.CompactTextString(m) }
func (*ExtractionResponse) ProtoMessage()    {}
func (*ExtractionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60183f17d85d4744, []int{6}
}

func (m *ExtractionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtractionResponse.Unmarshal(m, b)
}
func (m *ExtractionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtractionResponse.Marshal(b, m, deterministic)
}
func (m *ExtractionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtractionResponse.Merge(m, src)
}
func (m *ExtractionResponse) XXX_Size() int {
	return xxx_messageInfo_ExtractionResponse.Size(m)
}
func (m *ExtractionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtractionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExtractionResponse proto.InternalMessageInfo

func (m *ExtractionResponse) GetIsItemNameValid() bool {
	if m != nil {
		return m.IsItemNameValid
	}
	return false
}

func (m *ExtractionResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type CreateJobRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobRequest) Reset()         { *m = CreateJobRequest{} }
func (m *CreateJobRequest) String() string { return proto.CompactTextString(m) }
func (*CreateJobRequest) ProtoMessage()    {}
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60183f17d85d4744, []int{7}
}

func (m *CreateJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobRequest.Unmarshal(m, b)
}
func (m *CreateJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobRequest.Marshal(b, m, deterministic)
}
func (m *CreateJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobRequest.Merge(m, src)
}
func (m *CreateJobRequest) XXX_Size() int {
	return xxx_messageInfo_CreateJobRequest.Size(m)
}
func (m *CreateJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobRequest proto.InternalMessageInfo

type CreateJobResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobResponse) Reset()         { *m = CreateJobResponse{} }
func (m *CreateJobResponse) String() string { return proto.CompactTextString(m) }
func (*CreateJobResponse) ProtoMessage()    {}
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60183f17d85d4744, []int{8}
}

func (m *CreateJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobResponse.Unmarshal(m, b)
}
func (m *CreateJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobResponse.Marshal(b, m, deterministic)
}
func (m *CreateJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobResponse.Merge(m, src)
}
func (m *CreateJobResponse) XXX_Size() int {
	return xxx_messageInfo_CreateJobResponse.Size(m)
}
func (m *CreateJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobResponse proto.InternalMessageInfo

type DeleteJobRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteJobRequest) Reset()         { *m = DeleteJobRequest{} }
func (m *DeleteJobRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteJobRequest) ProtoMessage()    {}
func (*DeleteJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60183f17d85d4744, []int{9}
}

func (m *DeleteJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteJobRequest.Unmarshal(m, b)
}
func (m *DeleteJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteJobRequest.Marshal(b, m, deterministic)
}
func (m *DeleteJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteJobRequest.Merge(m, src)
}
func (m *DeleteJobRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteJobRequest.Size(m)
}
func (m *DeleteJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteJobRequest proto.InternalMessageInfo

type GetJobRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobRequest) Reset()         { *m = GetJobRequest{} }
func (m *GetJobRequest) String() string { return proto.CompactTextString(m) }
func (*GetJobRequest) ProtoMessage()    {}
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60183f17d85d4744, []int{10}
}

func (m *GetJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobRequest.Unmarshal(m, b)
}
func (m *GetJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobRequest.Marshal(b, m, deterministic)
}
func (m *GetJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobRequest.Merge(m, src)
}
func (m *GetJobRequest) XXX_Size() int {
	return xxx_messageInfo_GetJobRequest.Size(m)
}
func (m *GetJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobRequest proto.InternalMessageInfo

type Job struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_60183f17d85d4744, []int{11}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

type PredictionRequest struct {
	ItemId               string   `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictionRequest) Reset()         { *m = PredictionRequest{} }
func (m *PredictionRequest) String() string { return proto.CompactTextString(m) }
func (*PredictionRequest) ProtoMessage()    {}
func (*PredictionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60183f17d85d4744, []int{12}
}

func (m *PredictionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictionRequest.Unmarshal(m, b)
}
func (m *PredictionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictionRequest.Marshal(b, m, deterministic)
}
func (m *PredictionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictionRequest.Merge(m, src)
}
func (m *PredictionRequest) XXX_Size() int {
	return xxx_messageInfo_PredictionRequest.Size(m)
}
func (m *PredictionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PredictionRequest proto.InternalMessageInfo

func (m *PredictionRequest) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

type PredictionResponse struct {
	IsResourceValid      bool     `protobuf:"varint,1,opt,name=is_resource_valid,json=isResourceValid,proto3" json:"is_resource_valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictionResponse) Reset()         { *m = PredictionResponse{} }
func (m *PredictionResponse) String() string { return proto.CompactTextString(m) }
func (*PredictionResponse) ProtoMessage()    {}
func (*PredictionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60183f17d85d4744, []int{13}
}

func (m *PredictionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictionResponse.Unmarshal(m, b)
}
func (m *PredictionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictionResponse.Marshal(b, m, deterministic)
}
func (m *PredictionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictionResponse.Merge(m, src)
}
func (m *PredictionResponse) XXX_Size() int {
	return xxx_messageInfo_PredictionResponse.Size(m)
}
func (m *PredictionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PredictionResponse proto.InternalMessageInfo

func (m *PredictionResponse) GetIsResourceValid() bool {
	if m != nil {
		return m.IsResourceValid
	}
	return false
}

func init() {
	proto.RegisterType((*GenericShowRequest)(nil), "imdb.GenericShowRequest")
	proto.RegisterType((*CreateShowRequest)(nil), "imdb.CreateShowRequest")
	proto.RegisterType((*CreateShowResponse)(nil), "imdb.CreateShowResponse")
	proto.RegisterType((*Show)(nil), "imdb.Show")
	proto.RegisterType((*Empty)(nil), "imdb.Empty")
	proto.RegisterType((*ExtractionRequest)(nil), "imdb.ExtractionRequest")
	proto.RegisterType((*ExtractionResponse)(nil), "imdb.ExtractionResponse")
	proto.RegisterType((*CreateJobRequest)(nil), "imdb.CreateJobRequest")
	proto.RegisterType((*CreateJobResponse)(nil), "imdb.CreateJobResponse")
	proto.RegisterType((*DeleteJobRequest)(nil), "imdb.DeleteJobRequest")
	proto.RegisterType((*GetJobRequest)(nil), "imdb.GetJobRequest")
	proto.RegisterType((*Job)(nil), "imdb.Job")
	proto.RegisterType((*PredictionRequest)(nil), "imdb.PredictionRequest")
	proto.RegisterType((*PredictionResponse)(nil), "imdb.PredictionResponse")
}

func init() { proto.RegisterFile("imdb.proto", fileDescriptor_60183f17d85d4744) }

var fileDescriptor_60183f17d85d4744 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0x1d, 0xda, 0xe6, 0x63, 0x4a, 0x95, 0x66, 0x2a, 0x48, 0x14, 0x24, 0x3e, 0xf6, 0x84,
	0x0a, 0x54, 0x60, 0xc4, 0x15, 0x81, 0x48, 0x15, 0x25, 0x07, 0x84, 0x5c, 0x89, 0x1b, 0xb2, 0xd6,
	0xf6, 0x00, 0x8b, 0x62, 0x6f, 0xf0, 0x6e, 0x0a, 0xbc, 0x13, 0xcf, 0xc0, 0xb3, 0xa1, 0xf5, 0xee,
	0x26, 0xdb, 0x5a, 0x15, 0xdc, 0xb2, 0xff, 0x99, 0xc9, 0xcc, 0x6f, 0xe6, 0x2f, 0x03, 0x88, 0xb2,
	0xc8, 0xce, 0xd6, 0xb5, 0xd4, 0x12, 0xf7, 0xcd, 0x6f, 0xf6, 0x0c, 0x70, 0x4e, 0x15, 0xd5, 0x22,
	0xbf, 0xf8, 0x2a, 0x7f, 0x24, 0xf4, 0x7d, 0x43, 0x4a, 0xe3, 0x18, 0x7a, 0x42, 0x53, 0x99, 0x8a,
	0x62, 0xd2, 0x79, 0xd8, 0x79, 0x3c, 0x48, 0xba, 0xe6, 0xb9, 0x28, 0xd8, 0x73, 0x18, 0xbd, 0xab,
	0x89, 0x6b, 0x0a, 0xb3, 0xef, 0xc1, 0xa0, 0xc9, 0xae, 0x78, 0x49, 0x2e, 0xbf, 0x6f, 0x84, 0xf7,
	0xbc, 0x24, 0xf6, 0x0d, 0x30, 0xac, 0x50, 0x6b, 0x59, 0x29, 0xc2, 0x09, 0xf4, 0xf2, 0x46, 0xb5,
	0x0d, 0xfa, 0x89, 0x7f, 0x86, 0xad, 0x6f, 0x85, 0xad, 0xf1, 0x11, 0xdc, 0xd6, 0xa2, 0xa4, 0xd4,
	0xd7, 0xed, 0x35, 0xd1, 0x43, 0xa3, 0xd9, 0x06, 0x05, 0x7b, 0x00, 0xfb, 0xa6, 0xcb, 0xcd, 0xe3,
	0xf7, 0xe0, 0xe0, 0xbc, 0x5c, 0xeb, 0x5f, 0x86, 0xe3, 0xfc, 0xa7, 0xae, 0x79, 0xae, 0x85, 0xac,
	0xfe, 0x8b, 0x83, 0x03, 0x86, 0x15, 0x8e, 0xe3, 0x09, 0xa0, 0x50, 0xe9, 0xb6, 0x2a, 0xbd, 0xe4,
	0x2b, 0xe1, 0x91, 0x86, 0x42, 0x2d, 0x5c, 0xf5, 0x47, 0x23, 0xe3, 0x7d, 0x00, 0xb5, 0xc9, 0x73,
	0x52, 0xea, 0xf3, 0x66, 0xd5, 0xd0, 0xf5, 0x93, 0x40, 0x61, 0x08, 0xc7, 0x96, 0x64, 0x29, 0x33,
	0x37, 0x13, 0x3b, 0xf1, 0x0b, 0x6f, 0x34, 0xdb, 0xd5, 0x24, 0xce, 0x68, 0x45, 0x57, 0x12, 0x87,
	0x70, 0x34, 0x27, 0x1d, 0x08, 0x07, 0xb0, 0xb7, 0x94, 0x19, 0x7b, 0x0a, 0xa3, 0x0f, 0x35, 0x15,
	0xe2, 0x0a, 0xe9, 0x8d, 0x0b, 0x7a, 0x03, 0x18, 0x66, 0x3b, 0xca, 0x53, 0x18, 0x09, 0x95, 0xd6,
	0xa4, 0xe4, 0xa6, 0xce, 0x5b, 0x90, 0x89, 0xd3, 0x1b, 0xc8, 0xf8, 0x4f, 0x07, 0x86, 0x33, 0xae,
	0x79, 0xc6, 0x15, 0x5d, 0x50, 0x7d, 0x29, 0x72, 0xc2, 0x17, 0xd0, 0x9b, 0x93, 0x6e, 0x4e, 0x33,
	0x39, 0x6b, 0x2c, 0xd8, 0xf6, 0xdc, 0x14, 0x6c, 0xc4, 0x48, 0x2c, 0xc2, 0xb7, 0x00, 0x3b, 0xdb,
	0xe0, 0xd8, 0xc6, 0x5a, 0xd6, 0x9b, 0x4e, 0xda, 0x01, 0xb7, 0xa3, 0x08, 0x5f, 0x01, 0xd8, 0x2d,
	0xfd, 0xa3, 0xf1, 0xa1, 0x8d, 0x58, 0x63, 0x44, 0xf1, 0x27, 0x38, 0x76, 0x87, 0x96, 0xb5, 0x07,
	0x58, 0x00, 0x2e, 0x2a, 0xa1, 0x05, 0xd7, 0xb4, 0x33, 0x81, 0x9f, 0xaa, 0x65, 0x24, 0x3f, 0x55,
	0xdb, 0x2f, 0x2c, 0x8a, 0x7f, 0x77, 0x00, 0x96, 0x32, 0xf3, 0xff, 0xfc, 0x1a, 0x06, 0xdb, 0xfb,
	0xe2, 0xdd, 0x90, 0x66, 0x77, 0xca, 0xe9, 0xb8, 0xa5, 0x6f, 0x21, 0x4f, 0xa1, 0x6b, 0xcf, 0x8e,
	0x27, 0x1e, 0x30, 0x30, 0xc1, 0x74, 0x60, 0x45, 0x63, 0x84, 0x08, 0x63, 0x18, 0x6c, 0x6d, 0xe3,
	0x7b, 0x5d, 0xf7, 0xd1, 0xf5, 0x6d, 0x8c, 0xe1, 0x4e, 0x42, 0xb9, 0x2c, 0x4b, 0xaa, 0x0a, 0x6e,
	0x50, 0xdc, 0xe0, 0x71, 0x0a, 0xe3, 0x84, 0x6b, 0x51, 0x7d, 0xd9, 0xf9, 0xc5, 0x33, 0xcd, 0xe0,
	0xc8, 0x89, 0x36, 0xc3, 0x2f, 0xaa, 0xe5, 0x43, 0xbf, 0xa8, 0xb6, 0xe5, 0x58, 0x94, 0x75, 0x9b,
	0xcf, 0xd4, 0xcb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x80, 0xa8, 0xe0, 0xb4, 0x04, 0x00,
	0x00,
}
