
# ============ Build stage =============
FROM node:lts-alpine as build-stage
WORKDIR /usr/app/src
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# ========== Production stage ==========
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /usr/app/src/build /usr/share/nginx/html
COPY --from=build-stage /usr/app/src/default.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]